name: Validate

on:
  pull_request:
    branches: [main]

env:
  TZ: Asia/Shanghai

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get install -y arch-install-scripts debootstrap

    - name: Build
      run: |
        export ROOTFS_PATH="$(pwd)/rootfs"
        export MIRROR="http://azure.archive.ubuntu.com/ubuntu"
        sudo --preserve-env ./bootstrap.sh
